<?php
/**
 * The template used for displaying page content in page.php
 *
 * @package ThemeGrill
 * @subpackage Masonic
 * @since 1.0
 */
?>





<?php

function validate_booking($lab_first_name, $lab_last_name, $lab_age, $lab_purpose, $lab_waiver, $lab_card, $lab_phone, $lab_email, $lab_orientation, $lab_time, $lab_date, $lab_name, $lab_branch){
  $str_message = ""; 

  if(strlen($lab_phone) != 10 || !is_numeric($lab_phone)){
    $str_message .= "Please enter a valid phone number.\n";
  }   

  //check that the lab is available from the location 
  $check_lab_station = checkLabStation($lab_branch, $lab_name);

  if(count($check_lab_station) == 0){
    $str_message .= "An error has occurred. This lab isn't available from this branch. Please reload the page and try again.\n";  
  }

  $date_today = new Datetime(); 
  $date_selected = new Datetime($lab_date); 
  $date_interval = ceil(($date_selected->format('U') - $date_today->format('U')) / (60*60*24));
  if($date_interval < 3 || $date_interval > 30){
    $str_message .= "Date Unavailable. Please select a later date.\n";
  }  

  $check_library_card = checkLibraryCard($lab_name, $lab_card, $lab_date);
  if(count($check_library_card) > 0){
    $str_message .= "You can only book the same lab once per day with the same library card.\n";
  }
  
  $check_name = checkName($lab_name, $first_name, $last_name, $lab_date);  
  if(count($check_name) > 0){
    $str_message .= "You have already booked this lab for the specified day.\n";
  }

  $check_reservation = checkReservation($lab_name, $lab_date, $lab_time);
  if(count($check_reservation) > 0){
    $str_message .= "This lab has already been booked at the requested time.\n";
  }  
   

  return $str_message; 

}


$time_options = array(
  "10am"=>"10:00am - 12:00pm",
  "11am"=>"11:00am - 2:00pm",
  "12pm"=>"12:00pm - 2:00pm",
  "2pm"=>"2:00pm - 4:00pm",
  "4pm"=>"4:00pm - 6:00pm",
  "5pm"=>"5:00pm - 8:00pm",
  "6pm"=>"6:00pm - 8:00pm",
  "10h"=>"10:00am - 11:00am",		    
  "11h"=>"11:00am - 12:00pm",
  "12h"=>"12:00pm - 1:00pm",
  "13h"=>"1:00pm - 2:00pm",
  "14h"=>"2:00pm - 3:00pm",
  "15h"=>"3:00pm - 4:00pm",
  "16h"=>"4:00pm - 5:00pm",
  "17h"=>"5:00pm - 6:00pm",
  "18h"=>"6:00pm - 7:00pm",
  "19h"=>"7:00pm - 8:00pm");		

$lab_message = "";
$lab_success = "";
$all_labs = getLabs();

$labs = array();
$ccrl_list = array();
$pbrl_list = array();
$special_list = array();
foreach($all_labs as $each_lab){
    $labs[$each_lab->short_name] = $each_lab->full_name;
    if($each_lab->branch_id == 11){
        $special_list['11'][$each_lab->type][$each_lab->short_name] = $each_lab->full_name;
    }

    if($each_lab->branch_id == 7){
        $special_list['7'][$each_lab->type][$each_lab->short_name] = $each_lab->full_name;
    }    
}







if(isset($_POST['submit'])){
    //prep mail 
    $first_name = filter_var($_POST['lab_first_name'], FILTER_SANITIZE_STRING);
    $branch = filter_var($_POST['branch'], FILTER_SANITIZE_STRING);
    $lab_name = filter_var($_POST['lab_name'], FILTER_SANITIZE_STRING);
    $lab_date = filter_var($_POST['lab_date'], FILTER_SANITIZE_STRING);
    $lab_time_slot = filter_var($_POST['lab_time'], FILTER_SANITIZE_STRING);
    $last_name = filter_var($_POST['lab_last_name'], FILTER_SANITIZE_STRING);
    $lab_age = filter_var($_POST['lab_age'], FILTER_SANITIZE_STRING);
    $lab_agreement = filter_var($_POST['lab_agreement'], FILTER_SANITIZE_STRING);
    $lab_purpose = filter_var($_POST['lab_purpose'], FILTER_SANITIZE_STRING);
    $lab_library_card = filter_var($_POST['lab_library_card'], FILTER_SANITIZE_STRING);
    $lab_email = filter_var($_POST['lab_email'], FILTER_SANITIZE_EMAIL);
    $lab_telephone = filter_var($_POST['lab_telephone'], FILTER_SANITIZE_STRING);
    $lab_orientation = filter_var($_POST['lab_orientation'], FILTER_SANITIZE_STRING);

    if(!empty($_FILES['lab_file']['name'])){

      if ( ! function_exists( 'wp_handle_upload' ) ) {
          require_once( ABSPATH . 'wp-admin/includes/file.php' );          
      }

      $uploadedfile = $_FILES['lab_file'];

      $upload_overrides = array( 'test_form' => false );

      $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

      if ( $movefile && ! isset( $movefile['error'] ) ) {
          $file_location = $movefile['file'];
      } else {
          /**
          * Error generated by _wp_handle_upload()
          * @see _wp_handle_upload() in wp-admin/includes/file.php
          */
          echo $movefile['error'];
          $lab_message .= "Unable to upload your file.\n";  
      }
    }

    $results = validate_booking($first_name, $last_name, $lab_age, $lab_purpose, $lab_agreement, $lab_library_card, $lab_telephone, $lab_email, $lab_orientation, $lab_time_slot, $lab_date, $lab_name, $branch);
    if(strlen($results) == 0){
      $to = "david.heng@vaughan.ca";  
      //$to = "Librarian.Librarian@vaughan.ca";
      /* email details */
      $subject = "Request to Reserve a Lab";						
  
      $message = "The following customer wants to reserve a lab:\n".
      "\n".
      "Name:  ". $first_name . " " . $last_name . "\n" .
      "Age:  ". $lab_age . "\n".
      "Customer Agreement Form Signed?:  ". $lab_agreement . "\n".
      "Purpose:  ". $lab_purpose . "\n".
      "Telephone:  ". $lab_telephone . "\n".
      "Library Card Number:  ". $lab_library_card . "\n".
      "Email Address:  ". $lab_email . "\n".
      "Lab:  ". $labs[$lab_name] . "\n".
      "Date:  ". $lab_date . "\n".
      "Time Slot:  ". $time_options[$lab_time_slot] . "\n".																						
      "Orientation Required: ". $lab_orientation . "\n\n";
                  
      $content = $message;
      
      $headers[] = 'From: Vaughan Public Libraries <librarian.librarian@vaughan.ca>';            
      
      $attachment = array( $file_location );
      
      wp_mail($to, $subject, $content, $headers, $attachment);
      $lab_success = "Thank you. Your request will be processed and a librarian will get back to you shortly.";
    }
    else{
      $lab_message = $results;
    }            
   
/*
          $mail = new PHPMailer();
					$mail->From = 'Librarian.Librarian@vaughan.ca';
					$mail->FromName = 'Vaughan Public Libraries';
					$mail->Subject = $subject;
					$mail->addReplyTo($lab_email);
					$mail->Body = $message;
					//$mail->AddAddress( 'Librarian.Librarian@vaughan.ca' );
          $mail->AddAddress( 'david.heng@vaughan.ca' );					
					$mail->Send();
          echo "mail sent";*/



}


?>

<article id="post-<?php the_ID(); ?>" <?php post_class('blog-post'); ?>>
  <div class="entry-content">
    <?php if(strlen($lab_message) > 0){ ?>
      <div class="notify-margin notify notify-red">Form Submission Error:<br><?php echo $lab_message; ?></div>
    <?php }else if(strlen($lab_success) > 0){ ?>
      <div class="notify-margin notify notify-green"><?php echo $lab_success; ?></div>
    <?php } ?>

    <?php the_content(); ?>

		
    <form action="/shareit/labs/" method="post" enctype="multipart/form-data" onsubmit="return validateBooking();">			
				<fieldset>
          <p>Please complete all fields with an asterisk (*). </p>
					
						
          <p> <label for="lab_branch">Branch<sup>*</sup>:  </label> 
            <select name="branch" title="Local Branch" id="branch" onchange="changeLabs()" required>              
              <option value="11">Civic Centre Resource Library</option>
              <option value="7">Pierre Berton Resource Library</option>
            </select>
          </p>

           <p> <label for="lab_name">Lab<sup>*</sup>:  </label> 
            <select name="lab_name" id="lab_name" onchange="limitTime();">
              <option value="">- Select Lab -</option>                                      
            </select>          
          </p>

          
           <p> <label for="lab_date">Date<sup>*</sup>:  </label> 
           <input name="lab_date" size="15" maxlength="15" onblur="limitTime()" id="lab_date"  type="text" required>
          </p>

           <p> <label for="lab_time">Time Slot<sup>*</sup>:  </label> 
            <select name="lab_time" id="lab_time" required>
              <option value="">- Select Lab and Date -</option>
            </select>              
          </p>
          
           <p> <label for="lab_first_name">First Name<sup>*</sup>:  </label> 
            <input type="text" name="lab_first_name" id="lab_first_name" size="50" required />
          </p>

           <p> <label for="lab_last_name">Last Name<sup>*</sup>:  </label> 
           <input type="text" name="lab_last_name" id="lab_last_name" size="50" required />
          </p>

           <p> <label for="lab_age">Age<sup>*</sup>:  </label> 
            <input type="text" name="lab_age" id="lab_age" size="50" required />
          </p>

           <p> <label for="lab_agreement">Customer Agreement Form Signed and Returned?<sup>*</sup>:  </label> 
            <input type="radio" id="lab_agreement" value="Yes" name="lab_agreement">Yes
            <input type="radio" id="lab_agreement" value="No" name="lab_agreement" checked>No        
          </p>

           <p> <label for="lab_purpose">Purpose<sup>*</sup>:  </label> 
            <select name="lab_purpose" id="lab_purpose" required>
              <option value=""> </option>

              <option value="work">Work</option>

              <option value="school">School</option>
              
              <option value="hobby">Hobby</option>
            </select>              
          </p>

           <p> <label for="lab_library_card">Library Card<sup>*</sup>:  </label> 
           <input type="text" name="lab_library_card" id="lab_library_card" required />
          </p>
     
           <p> <label for="lab_email">Email<sup>*</sup>:  </label> 
            <input type="email" name="lab_email" id="lab_email" size="50" required />
          </p>

           <p> <label for="lab_telephone">Telephone<sup>*</sup>:  </label> 
            <input type="text" name="lab_telephone" id="lab_telephone" required />
          </p>

           <p> <label for="lab_orientation">Orientation Required<sup>*</sup>:  </label> 
            <input type="radio" id="lab_orientation" value="Yes" name="lab_orientation" checked>Yes
            <input type="radio" id="lab_orientation" value="No" name="lab_orientation">No                  
          </p>

           <p> <label for="lab_file">For 3d Printing bookings. Upload your STL file (Max size: 2MB):  </label> 
            <br><input type="file" name="lab_file" id="lab_file">
          </p>											              

          <div id="form_errors"></div> 

          <div class="labs_email_reminder">
            Please check your email and spam folder for confirmation of your reservation. Please allow 3 business days for processing.
          </div>
          <p>
            <input type="submit" name="submit" id="submit" value="Submit Request">
          </p>											              
      </fieldset>
    </form>

      <?php
      wp_link_pages(array(
          'before' => '<div class="page-links">' . __('Pages:', 'masonic'),
          'after' => '</div>',
      ));
      ?>
   </div><!-- .entry-content -->


</article><!-- #post-## -->


<script type="text/javascript">
<?php 
    $ccrl_select = "";
    $pbrl_select = "";

    $ccrl_select .= "<optgroup label='Service'>";
        foreach ($special_list['11']['service'] as $key => $value){
            $ccrl_select .= "<option value='$key'>" . $value . "</option>";    
        }
    $ccrl_select .= "</optgroup>";
    $ccrl_select .= "<optgroup label='Space'>";
        foreach ($special_list['11']['space'] as $key => $value){
            $ccrl_select .= "<option value='$key'>" . $value . "</option>";    
        }                    
    $ccrl_select .= "</optgroup>";
    $ccrl_select .= "<optgroup label='Equipment'>";
        foreach ($special_list['11']['equipment'] as $key => $value){
            $ccrl_select .= "<option value='$key'>" . $value . "</option>";    
        }                    
    $ccrl_select .= "</optgroup>";

    
    if(isset($special_list['7'])){ 
        $pbrl_select .= "<optgroup label='Service'>";                                  
            foreach ($special_list['7']['service'] as $key => $value){
                $pbrl_select .= "<option value='$key'>" . $value . "</option>";    
            }                     
        $pbrl_select .= "</optgroup>";
        $pbrl_select .= "<optgroup label='Equipment'>";
            foreach ($special_list['7']['equipment'] as $key => $value){
                $pbrl_select .= "<option value='$key'>" . $value . "</option>";    
            }                     
        $pbrl_select .= "</optgroup>";
    }

    echo "var labs_ccrl =\"$ccrl_select\";";
    echo "var labs_pbrl =\"$pbrl_select\";";
?>

function changeLabs(){
    var val = jQuery('#branch').val();
    var select = jQuery('#lab_name');

    if(val == 7){
        select.empty().append(labs_pbrl);
    }
    if(val == 11){
        select.empty().append(labs_ccrl);
    }
}

function validateBooking(){
  var error_message = "";


  var age_field = document.getElementById("lab_age").val();
  //console.log(age_field);
  if(isNaN(age_field)){
    error_message += "Age must be an number.\n";     
  }

  //check date has been filled in: 
  var date_field = document.getElementById('lab_date').val();
  if(date_field.length == 0){
    error_message += "Please fill in the date field.\n";
     
  }

  if(document.getElementById('lab_file').files.length > 0){
    size = document.getElementById('lab_file').files[0].size; 
    if (size > 2096000) { 
      error_message += 'Your file size exceeds the limit allowed and cannot be uploaded.\n'; 
      
    } 
  }
  
  
  if(error_message.length > 0){
    alert("Errors:\n" + error_message);
    return false;
  }
  
  return true;
}


function limitTime(){

	//For non 3D Printing stations
	var weekendTime = [
		{value: "10am", text: "10:00am - 12:00pm"},
		{value: "12pm", text: "12:00pm - 2:00pm"},
		{value: "2pm", text: "2:00pm - 4:00pm"},
	];
	
	//For non 3D Printing Stations
	var weekdayTime = [
		{value: "10am", text: "10:00am - 12:00pm"},
		{value: "12pm", text: "12:00pm - 2:00pm"},
		{value: "2pm", text: "2:00pm - 4:00pm"},
		{value: "4pm", text: "4:00pm - 6:00pm"},
		{value: "6pm", text: "6:00pm - 8:00pm"},
	];
		
	//For 3D Printing Stations 	
	var weekdayTime_3d_stations = [
		{value: "11am", text: "11:00am - 2:00pm"},		    
		{value: "5pm", text: "5:00pm - 8:00pm"}    
	];

	var weekendTime_3d_stations = [
		{value: "11am", text: "11:00am - 2:00pm"}		
	];
  
  //For Oculus Rift
	var weekdayTime_oculus_stations = [
		{value: "10h", text: "10:00am - 11:00am"},		    
    {value: "11h", text: "11:00am - 12:00pm"},
    {value: "12h", text: "12:00pm - 1:00pm"},
    {value: "13h", text: "1:00pm - 2:00pm"},
    {value: "14h", text: "2:00pm - 3:00pm"},
    {value: "15h", text: "3:00pm - 4:00pm"},
    {value: "16h", text: "4:00pm - 5:00pm"},
    {value: "17h", text: "5:00pm - 6:00pm"},
    {value: "18h", text: "6:00pm - 7:00pm"},
    {value: "19h", text: "7:00pm - 8:00pm"}
	];

	var weekendTime_oculus_stations = [
		{value: "10h", text: "10:00am - 11:00am"},		    
    {value: "11h", text: "11:00am - 12:00pm"},
    {value: "12h", text: "12:00pm - 1:00pm"},
    {value: "13h", text: "1:00pm - 2:00pm"},
    {value: "14h", text: "2:00pm - 3:00pm"},
    {value: "15h", text: "3:00pm - 4:00pm"}	
	];  


	//console.log(jQuery('#LabDate').val());	 
	var chosen_date = jQuery('#lab_date').val();

	//if the date hasn't been chosen yet, we can just exit immediately.
	if(chosen_date == ""){
		return; 
	}

	var chosen_date_obj =new Date(chosen_date); 
	var day = chosen_date_obj.getDay();
	//console.log(day);
	//we are considering weekdays as tues - thurs and weekends as fri - sun as per Kristin 
	var isWeekend = (day == 4) || (day == 5) || (day == 6);  
	
	//clear all options from the start time select box 
	var select_time_slot_erase = document.getElementById("lab_time");
	var length = select_time_slot_erase.options.length;
	for (i = 0; i < length; i++) {
		select_time_slot_erase.options[0] = null;
	}
	
	var select_time_slot = document.getElementById("lab_time"),
			lab_choice = jQuery("#lab_name"),		
	option,
  i = 0;
  	

	//Populate the time slot options. Different for 3D Printing Stations. 
	if(lab_choice.val() == "3d_station_1" || lab_choice.val() == "3d_station_2" || lab_choice.val() == "3d_station_3" || lab_choice.val() == "carving_station"){
		if(isWeekend){
      il = weekendTime_3d_stations.length;
      for (; i < il; i += 1) {
          option = document.createElement('option');
          option.setAttribute('value', weekendTime_3d_stations[i].value);
          option.appendChild(document.createTextNode(weekendTime_3d_stations[i].text));
          select_time_slot.appendChild(option);
      }      
    }
    else{
      il = weekdayTime_3d_stations.length;
      for (; i < il; i += 1) {
          option = document.createElement('option');
          option.setAttribute('value', weekdayTime_3d_stations[i].value);
          option.appendChild(document.createTextNode(weekdayTime_3d_stations[i].text));
          select_time_slot.appendChild(option);
      }
    }
    		
	}
  else if(lab_choice.val() == "oculus_rift"){
		if(isWeekend){
      il = weekendTime_oculus_stations.length;
      for (; i < il; i += 1) {
          option = document.createElement('option');
          option.setAttribute('value', weekendTime_oculus_stations[i].value);
          option.appendChild(document.createTextNode(weekendTime_oculus_stations[i].text));
          select_time_slot.appendChild(option);
      }      
    }
    else{
      il = weekdayTime_oculus_stations.length;
      for (; i < il; i += 1) {
          option = document.createElement('option');
          option.setAttribute('value', weekdayTime_oculus_stations[i].value);
          option.appendChild(document.createTextNode(weekdayTime_oculus_stations[i].text));
          select_time_slot.appendChild(option);
      }
    }    		
	}
	else{	
		if(isWeekend){
			il = weekendTime.length;
			for (; i < il; i += 1) {
					option = document.createElement('option');
					option.setAttribute('value', weekendTime[i].value);
					option.appendChild(document.createTextNode(weekendTime[i].text));
					select_time_slot.appendChild(option);
			}
		}
		else{		
			il = weekdayTime.length;
			for (; i < il; i += 1) {
					option = document.createElement('option');
					option.setAttribute('value', weekdayTime[i].value);
					option.appendChild(document.createTextNode(weekdayTime[i].text));		
					select_time_slot.appendChild(option);
			}		
		}
	}
}

jQuery(document).ready(function() {
    //update the lab options
    changeLabs();

	// date picker restriction
	jQuery('#lab_date').Zebra_DatePicker({ 
		direction: [3, 27],
		disabled_dates: ['* * * 1',
      '09 10 2016',
      '24 12 2016',       
      '25 12 2016',  
      '26 12 2016', 
      '31 12 2016',
      '01 01 2017',
      '02 20 2017',
      '04 14 2017',
      '04 16 2017',
      '04 17 2017',
      '04 25 2017',
      '05 21 2017',
      '05 22 2017',
      '07 01 2017',
      '08 06 2017',
      '08 07 2017',
      '09 03 2017',
      '09 04 2017',
      '10 08 2017',
      '10 09 2017',
      '12 24 2017',
      '12 25 2017',
      '12 26 2017',
      '12 31 2017',
      '01 01 2018'       
    ],
  });
});


</script>